///
/// Simplest way to fail unit test
///

func int main():
  ret 1 //// exit-code 1
end

